### ISSUE TITLE
Site unaccessible

### ISSUE THREAD

**Issue by veronica320** [UKPLab/linspector-web#22]
Hi,

Thanks for putting together this great repo! I'm trying to access https://linspector.ukp.informatik.tu-darmstadt.de/ but it no longer works. Could you please help?

Thanks!

**Comment by maexe** [comment]
Hi, unfortunately the server is no longer online. If you want to run the project locally you might need to update it to a current version of AllenNLP or you can just use the data from here: https://github.com/UKPLab/linspector

Sorry for the late reply. Max
